<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260928000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create position and job_application tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE job_position (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                hash UUID NOT NULL UNIQUE,
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                required_skills JSONB NOT NULL,
                created_at TIMESTAMP(6) NOT NULL
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE job_application (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                hash UUID NOT NULL UNIQUE,
                job_position_id INTEGER NOT NULL REFERENCES job_position (id),
                candidate_full_name TEXT NOT NULL,
                candidate_email TEXT NOT NULL,
                candidate_phone TEXT NULL,
                notes TEXT NULL,
                cv_text TEXT NOT NULL,
                status TEXT NOT NULL CHECK (status IN ('received', 'enriched')),
                ai_summary TEXT NULL,
                ai_score SMALLINT NULL CHECK (ai_score BETWEEN 0 AND 100),
                applied_at TIMESTAMP(6) NOT NULL,
                enriched_at TIMESTAMP(6) NULL
            )
            SQL);

        $this->addSql('CREATE INDEX idx_job_application_applied_at ON job_application (applied_at DESC)');
        $this->addSql('CREATE INDEX idx_job_application_status_applied_at ON job_application (status, applied_at DESC)');
        $this->addSql('CREATE INDEX idx_job_application_job_position_id_applied_at ON job_application (job_position_id, applied_at DESC)');
        $this->addSql('CREATE INDEX idx_job_application_candidate_email ON job_application (candidate_email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE job_application');
        $this->addSql('DROP TABLE job_position');
    }
}
